version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080/api
      - NEXT_PUBLIC_WS_URL=ws://localhost:8080
    networks:
      - app-network
    restart: unless-stopped

# Docker networks
networks:
  app-network:
    driver: bridge
